version: '3.3'

services:
  spacy-training:
    image: ${DOCKER_IMAGE_NAME:-ilha/spacy-training}:${TAG:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - LANG_ISO
      - LANG_NAME
      - TRANING_TYPE