version: '3.3'

services:
  spacy-training:
    image: ${DOCKER_IMAGE_NAME:-ilha/spacy-training}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LANG_ISO
      - LANG_NAME
      - TRANING_TYPE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
